Guard xfail for polars test test_series_init_np_temporal_with_nat_15518 for NumPy>=2.5 (#23676)
Follow up to https://github.com/NVIDIA/cudf/pull/23635. Adds a numpy version guard since it only fails for specific numpy versions.

Fixes nightly failures https://github.com/NVIDIA/cudf/actions/runs/32007604769/job/95320256201#step:13:1742

```
FAILED py-polars/tests/unit/constructors/test_series.py::test_series_init_np_temporal_with_nat_15518 - [XPASS(strict)] DeprecationWarning from Numpy: https://github.com/pola-rs/polars/pull/28782
```

Authors:
  - Matthew Murray (https://github.com/Matt711)

Approvers:
  - Matthew Roeschke (https://github.com/mroeschke)

URL: https://github.com/NVIDIA/cudf/pull/23676