Ensure ParquetOptions.prefetch_file_metadata value of Unspecified is serializable (#23684)
After https://github.com/NVIDIA/cudf/pull/23558, attempting to write json benchmark results of `ParquetOptions.prefetch_file_metadata` with a value of `Unspecified` will error with 

```python
  File "/opt/conda/lib/python3.14/json/encoder.py" line 182 in default

    raise TypeError(f'Object of type {o.__class__.__name__} '

                    f'is not JSON serializable')

TypeError: Object of type Unspecified is not JSON serializable

when serializing dict item 'prefetch_file_metadata'

when serializing dict item 'parquet_options'

when serializing dict item 'config_options'

when serializing dict item 'config_options'
```

This PR just represents `Unspecified` and `None` in the serialized JSON. 

From a benchmarking result, this is a little unsatisfactory because `None` is faithful to the "user input" but isn't entirely clear regarding "did `prefetch_file_metadata` happen?" But that's a larger change that can be tackled later, i.e. can we write an engine config result _with knowledge_ about how `prefetch_file_metadata` was resolved

Authors:
  - Matthew Roeschke (https://github.com/mroeschke)

Approvers:
  - Matthew Murray (https://github.com/Matt711)

URL: https://github.com/NVIDIA/cudf/pull/23684