Remove `XPASS`ing datetime tests from pandas `XFAIL` set (#23866)
cuDF CI is currently failing because of these two test (e.g. https://github.com/NVIDIA/cudf/actions/runs/33031711211/job/98390070327?pr=23847)
```

FAILED tests/tools/test_to_datetime.py::TestTimeConversionFormats::test_to_datetime_format_weeks[True-2013020-%Y%U%w-2013-01-13] - [XPASS(strict)] AssertionError: assert Timestamp('2013-01-19 00:00:00') == Timestamp('2013-01-13 00:00:00')
FAILED tests/tools/test_to_datetime.py::TestTimeConversionFormats::test_to_datetime_format_weeks[False-2013020-%Y%U%w-2013-01-13] - [XPASS(strict)] AssertionError: assert Timestamp('2013-01-19 00:00:00') == Timestamp('2013-01-13 00:00:00')

```

I do not know what happened to cause them to start passing recently.

Authors:
  - Matthew Murray (https://github.com/Matt711)

Approvers:
  - Lawrence Mitchell (https://github.com/wence-)
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/NVIDIA/cudf/pull/23866