Add missing include for std::cerr in debug build (#23780)
Fixes debug build error by adding a missing include for `std::cerr`:

```
/cudf/cpp/src/utilities/stream_pool.cpp: In destructor 'virtual cudf::detail::cuda_event::~cuda_event()':
/cudf/cpp/src/utilities/stream_pool.cpp:49:12: error: 'cerr' is not a member of 'std'
   49 |       std::cerr << "CUDA Error detected. " << cudaGetErrorName(status__) << " " \
      |            ^~~~
/cudf/cpp/src/utilities/stream_pool.cpp:62:27: note: in expansion of macro 'CUDF_ASSERT_CUDA_SUCCESS'
   62 |   virtual ~cuda_event() { CUDF_ASSERT_CUDA_SUCCESS(cudaEventDestroy(e_)); }
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
/cudf/cpp/src/utilities/stream_pool.cpp:18:1: note: 'std::cerr' is defined in header '<iostream>'; this is probably fixable by adding '#include <iostream>'
```

Authors:
  - David Wendt (https://github.com/davidwendt)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - Lawrence Mitchell (https://github.com/wence-)
  - Yunsong Wang (https://github.com/PointKernel)

URL: https://github.com/NVIDIA/cudf/pull/23780